package ExceptionHandling;

public class Program1 
{
//using try catch block
	public static void main(String[] args)
	{
		//run  time exception 
		
		int a=50,b=0,c;
		try
		{
		c=a/b;
		System.out.println(c);
		}
		catch(Exception ae)
		{System.out.println("exception due to number divided by zero");
			ae.printStackTrace();
		}
		System.out.println("exception handling achived");
		//
		
	}
}
